### ISSUE TITLE
Backend - Create Models for User

### ISSUE THREAD

**Issue by adeniranjohn** [ALCOpenSource/conversational-app-team5#13]
Create Models for User

**Comment by aaademosu** [comment]
We already have a usermodel via firebase: https://firebase.google.com/docs/reference/js/auth.user

See User Properties
https://firebase.google.com/docs/reference/js/auth.userinfo#properties

**Comment by aaademosu** [comment]
pull request for this; https://github.com/ALCOpenSource/conversational-app-team5/pull/25
