### ISSUE TITLE
Error building front-end

### ISSUE THREAD

**Issue by aaademosu** [ALCOpenSource/conversational-app-team5#3]
Building the front-end returns errors about missing dependencies.

![image](https://user-images.githubusercontent.com/2017630/198148672-aad8d9bb-1076-4d15-94e2-6a7e7025eb33.png)

**Comment by adeniranjohn** [comment]
I tested before installing. Did you do npm install on the repo?

**Comment by aaademosu** [comment]
Installing @material-ui/core@^4.0.0 resolves this.
