### ISSUE TITLE
FrontEnd -  Login Form 

### ISSUE THREAD

**Issue by adeniranjohn** [ALCOpenSource/conversational-app-team5#7]
Login form using email and password
- with a google sign in button
- with a signup button

**Comment by aaademosu** [comment]
This has already being addressed with the integration with firebase. Related commits in the pull; https://github.com/ALCOpenSource/conversational-app-team5/pull/4

![image](https://user-images.githubusercontent.com/2017630/198519185-f89cc1ec-1e98-4985-b86b-58a82aeb8d2b.png)
