### ISSUE TITLE
Frontend - Registration Form 

### ISSUE THREAD

**Issue by adeniranjohn** [ALCOpenSource/conversational-app-team5#8]
Create a Registration form 

User
- name - String
- phone number - String 
- email - String
- password - String

**Comment by aaademosu** [comment]
Do we still need this? Since we are leveraging firebase auth

**Comment by adeniranjohn** [comment]
Yes, you are correct but initializing from backend with a routing endpoint.

**Comment by aaademosu** [comment]
Is having the registration form and backend endpoint a specific requirement. The firebase ui provided by the auth library already takes care of this.

You can see the behaviour here: https://masterminds-9786b.web.app

**Comment by adeniranjohn** [comment]
Yeah that’s true.

You will have to be meet with Àṣàbi to guide her through on how to implement. 
We will be meeting today. 
Thanks 🙏🏿
